"""sync

Revision ID: 48e9af67846f
Revises: b18f9f578fab
Create Date: 2025-10-13 16:38:32.991239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e9af67846f'
down_revision = 'b18f9f578fab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
