"""auto migration

Revision ID: b18f9f578fab
Revises: e9b6bf937780
Create Date: 2025-10-13 15:57:54.199256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18f9f578fab'
down_revision = 'e9b6bf937780'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
